name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or your default branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SERVICES_TO_PUSH: web,app,background

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Parse docker-compose file
      id: docker_compose
      run: |
        services=$(yq e '.services | keys | join(",")' docker-compose.yml)
        echo "SERVICES=$services" >> $GITHUB_OUTPUT

    - name: Build and push images
      run: |
        IFS=',' read -ra SERVICES <<< "${{ env.SERVICES_TO_PUSH }}"
        for service in "${SERVICES[@]}"; do
          echo "Processing service: $service"
          
          context=$(yq e ".services.$service.build.context" docker-compose.yml)
          echo "Context for $service: $context"
          
          dockerfile=$(yq e ".services.$service.build.dockerfile" docker-compose.yml)
          if [ "$dockerfile" = "null" ]; then
            dockerfile="$context/Dockerfile"
          fi
          echo "Dockerfile for $service: $dockerfile"
          
          echo "Building image for $service..."
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$service:latest -f $dockerfile $context
          
          echo "Pushing image for $service..."
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$service:latest
          
          echo "Completed processing for $service"
          echo "-----------------------------------"
        done
