name: Reveal Secrets

on:
  workflow_dispatch:

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        env:
          ALL_SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "WARNING: This action reveals sensitive information. Use with caution!" > secrets.txt
          echo "Secrets:" >> secrets.txt
          echo "$ALL_SECRETS" | jq '.' >> secrets.txt
          echo "IMPORTANT: Please delete these secrets artifact after use!" >> secrets.txt
      - name: Upload Secrets as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secrets
          path: secrets.txt
