name: Reveal Secrets

on:
  workflow_dispatch:

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        env:
          ALL_SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "WARNING: This action reveals sensitive information. Use with caution!"
          echo "Secrets:"
          echo "$ALL_SECRETS" | jq '.'
