name: VM Initialization

on:
  workflow_dispatch:

env:
  ROOT_DIRECTORY: /opt

jobs:
  initialize_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker and the plugins
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            mkdir -p ~/.docker/cli-plugins
            curl https://raw.githubusercontent.com/wowu/docker-rollout/master/docker-rollout -o ~/.docker/cli-plugins/docker-rollout
            chmod +x ~/.docker/cli-plugins/docker-rollout

      - name: Install Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: Restart Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if command -v systemctl >/dev/null 2>&1; then
              sudo systemctl restart docker
            elif command -v service >/dev/null 2>&1; then
              sudo service docker restart
            elif [ -f /etc/init.d/docker ]; then
              sudo /etc/init.d/docker restart
            else
              echo "Unable to restart Docker. Please restart it manually."
              exit 1
            fi

      - name: Validate Docker and Docker Compose Installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Validate Docker installation
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed or not in PATH"
              exit 1
            fi
            docker_version=$(docker --version)
            echo "Docker version: $docker_version"

            # Validate Docker Compose installation
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose is not installed or not in PATH"
              exit 1
            fi
            compose_version=$(docker-compose --version)
            echo "Docker Compose version: $compose_version"

            echo "Docker and docker compose have been installed. Server is ready to use 🎉🥳"
